#!/usr/bin/env python3
"""
analysis_boron.py
-----------------
Analyzes ROOT files generated by run_simulations_boron.py.

For each boron fraction (BORON_FRACTIONS) reads three ntuples:
  - ParticulasDetector  (ID=0): particles reaching the sensitive detector
  - ProductosCaptura    (ID=1): particles born in graphene from B-10 neutron capture
  - RangoIones          (ID=2): range of alpha and Li-7 ions in the material

Graphene thickness is fixed at GRAPHENE_UM µm.

Plots saved to python/plots_boron/:
  01  Capture efficiency vs boron fraction
  02  Particles created in graphene vs boron fraction
  03  Particles reaching the detector vs boron fraction (log scale)
  04  Fraction of created particles reaching the detector vs boron fraction
  05  Creation energy spectra at selected boron fraction
  06  Detector energy spectra at selected boron fraction (log y-scale)
  07  Creation vs detection energy comparison for selected boron fraction
  08  Mean ion range vs boron fraction
  09  All three species energies in one figure
  00  Summary 2×2 panel
"""

import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import AutoMinorLocator
import uproot

# ── Paths ─────────────────────────────────────────────────────────────────────
PROJECT_DIR = Path(__file__).resolve().parent.parent
BUILD_DIR   = PROJECT_DIR / "build"
PLOT_DIR    = Path(__file__).resolve().parent / "plots_boron"
PLOT_DIR.mkdir(exist_ok=True)

# Deben coincidir con run_simulations_boron.py
BORON_FRACTIONS = [0.01, 0.02, 0.03, 0.05, 0.07, 0.10, 0.15, 0.20, 0.25, 0.30]
GRAPHENE_UM     = 20       # espesor fijo
N_NEUTRONS      = 100_000

# Fracción seleccionada para espectros de energía detallados
SELECTED_FRACTION = 0.05   # 5 %

# ── Global style ───────────────────────────────────────────────────────────────
plt.rcParams.update({
    "figure.dpi"     : 120,
    "axes.titlesize" : 13,
    "axes.labelsize" : 12,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "legend.fontsize": 9,
    "lines.linewidth": 1.4,
    "axes.grid"      : True,
    "grid.alpha"     : 0.4,
})

COLORS = {
    "alpha": "#e74c3c",
    "Li7"  : "#3498db",
    "gamma": "#f39c12",
    "other": "#9b59b6",
}

PARTICLE_LABELS = {
    "alpha": r"$\alpha$",
    "Li7"  : "Li-7",
    "gamma": r"$\gamma$",
}

PARTICLE_ALIASES = {
    "alpha": ["alpha", "Alpha", "He4"],
    "Li7"  : ["Li7", "lithium7", "Li-7"],
    "Li6"  : ["Li6", "lithium6", "Li-6"],
    "gamma": ["gamma", "Gamma"],
}

PARTICLES = ["alpha", "Li7", "gamma"]


def normalize_particle(name: str) -> str:
    for key, aliases in PARTICLE_ALIASES.items():
        if name in aliases:
            return key
    return "other"


def root_name(fraction: float) -> str:
    pct = fraction * 100
    return f"output_B{pct:.2f}pct.root"


# ── ROOT loader ────────────────────────────────────────────────────────────────
def load_root(fraction: float) -> dict | None:
    path = BUILD_DIR / root_name(fraction)
    if not path.exists():
        print(f"  [WARN] Not found: {path.name}")
        return None

    try:
        f = uproot.open(str(path))

        def fix_strings(df: pd.DataFrame) -> pd.DataFrame:
            for col in df.columns:
                if df[col].dtype == object or "awkward" in str(type(df[col].dtype)).lower():
                    df[col] = df[col].apply(lambda x: str(x) if not isinstance(x, str) else x)
            return df

        det = fix_strings(f["ParticulasDetector"].arrays(library="pd"))
        det["ParticleNorm"] = det["ParticleType"].apply(normalize_particle)

        cap = fix_strings(f["ProductosCaptura"].arrays(library="pd"))
        cap["ParticleNorm"] = cap["ParticleType"].apply(normalize_particle)

        rng = fix_strings(f["RangoIones"].arrays(library="pd"))
        rng["ParticleNorm"] = rng["ParticleType"].apply(normalize_particle)

        return {"detector": det, "captura": cap, "rango": rng}

    except Exception as e:
        print(f"  [ERROR] Reading {path.name}: {e}")
        return None


# ── Metrics ────────────────────────────────────────────────────────────────────
def compute_metrics(data_by_fraction: dict) -> pd.DataFrame:
    rows = []
    for frac, data in sorted(data_by_fraction.items()):
        cap = data["captura"]
        det = data["detector"]
        rng = data["rango"]

        row = {"boron_pct": frac * 100}

        for p in PARTICLES:
            row[f"created_{p}"] = (cap["ParticleNorm"] == p).sum()

        row["n_captures"]   = cap[cap["ParticleNorm"] == "alpha"]["EventID"].nunique()
        row["efficiency_%"] = 100.0 * row["n_captures"] / N_NEUTRONS

        for p in PARTICLES:
            mask = (det["ParticleNorm"] == p) & (det["VertexVolume"] == "graphene")
            row[f"det_{p}"] = mask.sum()

        for p in ["alpha", "Li7"]:
            mask = rng["ParticleNorm"] == p
            row[f"range_{p}_um"] = rng.loc[mask, "TrackLength_um"].mean() if mask.any() else np.nan

        rows.append(row)
    return pd.DataFrame(rows)


# ── Helpers ────────────────────────────────────────────────────────────────────
def save(fig: plt.Figure, name: str):
    path = PLOT_DIR / name
    fig.savefig(str(path), bbox_inches="tight")
    plt.close(fig)
    print(f"  [PLOT] {path.name}")


def minor_ticks(ax):
    ax.xaxis.set_minor_locator(AutoMinorLocator())
    ax.yaxis.set_minor_locator(AutoMinorLocator())


def xlabel_boron():
    return "B-10 fraction in graphene (%)"


# ══════════════════════════════════════════════════════════════════════════════
# PLOTS
# ══════════════════════════════════════════════════════════════════════════════

# ── 01. Capture efficiency vs boron fraction ───────────────────────────────────
def plot_efficiency(df: pd.DataFrame):
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(df["boron_pct"], df["efficiency_%"],
            "o", color="#e74c3c", ms=7, label="Capture efficiency")
    ax.set_xlabel(xlabel_boron())
    ax.set_ylabel("Capture efficiency (%)")
    ax.set_title(f"Neutron Capture Efficiency vs Boron Fraction\n"
                 f"(Graphene thickness = {GRAPHENE_UM} µm)")
    ax.set_xlim(0, None)
    ax.set_ylim(0, None)
    minor_ticks(ax)

    idx_max = df["efficiency_%"].idxmax()
    ax.annotate(
        f'{df.loc[idx_max, "efficiency_%"]:.2f}%\n@ {df.loc[idx_max, "boron_pct"]:.1f} %',
        xy=(df.loc[idx_max, "boron_pct"], df.loc[idx_max, "efficiency_%"]),
        xytext=(df.loc[idx_max, "boron_pct"] + 1, df.loc[idx_max, "efficiency_%"] * 0.90),
        arrowprops=dict(arrowstyle="->", color="black"),
        fontsize=9,
    )
    ax.legend()
    fig.tight_layout()
    save(fig, "01_capture_efficiency_vs_boron.png")


# ── 02. Particles created in graphene vs boron fraction ───────────────────────
def plot_created_particles(df: pd.DataFrame):
    fig, ax = plt.subplots(figsize=(9, 5))
    for p in PARTICLES:
        ax.plot(df["boron_pct"], df[f"created_{p}"],
                "o", color=COLORS[p], ms=6, label=PARTICLE_LABELS[p])
    ax.set_xlabel(xlabel_boron())
    ax.set_ylabel("Number of particles created")
    ax.set_title(f"Particles Created by Neutron Capture vs Boron Fraction\n"
                 f"(Graphene thickness = {GRAPHENE_UM} µm)")
    ax.legend()
    minor_ticks(ax)
    fig.tight_layout()
    save(fig, "02_particles_created_vs_boron.png")


# ── 03. Particles reaching the detector vs boron fraction ─────────────────────
def plot_detected_particles(df: pd.DataFrame):
    fig, (ax_log, ax_ions) = plt.subplots(1, 2, figsize=(14, 5))

    for p in PARTICLES:
        ax_log.plot(df["boron_pct"], df[f"det_{p}"],
                    "s", color=COLORS[p], ms=6, label=PARTICLE_LABELS[p])
    ax_log.set_yscale("log")
    ax_log.set_xlabel(xlabel_boron())
    ax_log.set_ylabel("Particles reaching detector (log scale)")
    ax_log.set_title("All Species — Log Scale")
    ax_log.legend()
    ax_log.xaxis.set_minor_locator(AutoMinorLocator())

    for p in ["alpha", "Li7"]:
        ax_ions.plot(df["boron_pct"], df[f"det_{p}"],
                     "s", color=COLORS[p], ms=6, label=PARTICLE_LABELS[p])
    ax_ions.set_xlabel(xlabel_boron())
    ax_ions.set_ylabel("Particles reaching detector")
    ax_ions.set_title(r"Ions Only ($\alpha$ and Li-7) — Linear Scale")
    ax_ions.legend()
    minor_ticks(ax_ions)

    fig.suptitle(f"Particles from Graphene Reaching the Detector vs Boron Fraction\n"
                 f"(Graphene thickness = {GRAPHENE_UM} µm)",
                 fontsize=13)
    fig.tight_layout()
    save(fig, "03_particles_detector_vs_boron.png")


# ── 04. Transmission fraction: created → detector ─────────────────────────────
def plot_transmission_fraction(df: pd.DataFrame):
    fig, ax = plt.subplots(figsize=(9, 5))
    for p in PARTICLES:
        created = df[f"created_{p}"]
        det     = df[f"det_{p}"]
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            frac = np.where(created > 0, 100.0 * det / created, 0.0)
        ax.plot(df["boron_pct"], frac,
                "^", color=COLORS[p], ms=6, label=PARTICLE_LABELS[p])
    ax.set_xlabel(xlabel_boron())
    ax.set_ylabel("Fraction reaching detector (%)")
    ax.set_title(f"Fraction of Created Particles Reaching the Detector vs Boron Fraction\n"
                 f"(Graphene thickness = {GRAPHENE_UM} µm)")
    ax.set_ylim(0, None)
    ax.legend()
    minor_ticks(ax)
    fig.tight_layout()
    save(fig, "04_transmission_fraction_vs_boron.png")


# ── 05. Creation energy spectra at selected boron fraction ─────────────────────
def plot_creation_spectra(data_by_fraction: dict):
    key = SELECTED_FRACTION
    if key not in data_by_fraction:
        print(f"  [WARN] plot 05: fraction {key*100:.2f} % not available")
        return

    cap = data_by_fraction[key]["captura"]
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    xlims = {"alpha": None, "Li7": None, "gamma": (0, 2)}

    for ax, p in zip(axes, PARTICLES):
        mask = cap["ParticleNorm"] == p
        vals = cap.loc[mask, "KineticEnergy_MeV"].values
        if len(vals) == 0:
            ax.set_visible(False)
            continue
        xmax = xlims[p][1] if xlims[p] else vals.max() * 1.05
        bins = np.linspace(0, xmax, 70)
        ax.hist(vals, bins=bins, histtype="stepfilled",
                color=COLORS[p], alpha=0.75, edgecolor=COLORS[p], lw=1.2)
        ax.set_xlabel("Creation kinetic energy (MeV)")
        ax.set_ylabel("Counts")
        ax.set_title(f"{PARTICLE_LABELS[p]}")
        if xlims[p]:
            ax.set_xlim(*xlims[p])
        minor_ticks(ax)

    fig.suptitle(
        f"Creation Energy Spectra — B-10 fraction = {SELECTED_FRACTION*100:.1f} %  "
        f"|  Thickness = {GRAPHENE_UM} µm  ({N_NEUTRONS:,} neutrons)",
        fontsize=13,
    )
    fig.tight_layout()
    save(fig, "05_creation_energy_spectra.png")


# ── 06. Detector energy spectra at selected boron fraction ─────────────────────
def plot_detector_spectra(data_by_fraction: dict):
    key = SELECTED_FRACTION
    if key not in data_by_fraction:
        print(f"  [WARN] plot 06: fraction {key*100:.2f} % not available")
        return

    det = data_by_fraction[key]["detector"]
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    xlims = {"alpha": None, "Li7": None, "gamma": (0, 2000)}

    for ax, p in zip(axes, PARTICLES):
        mask = (det["ParticleNorm"] == p) & (det["VertexVolume"] == "graphene")
        vals = det.loc[mask, "KineticEnergy_keV"].values
        if len(vals) == 0:
            ax.set_visible(False)
            continue
        xmax = xlims[p][1] if xlims[p] else vals.max() * 1.05
        bins = np.linspace(0, xmax, 70)
        ax.hist(vals, bins=bins, histtype="stepfilled",
                color=COLORS[p], alpha=0.75, edgecolor=COLORS[p], lw=1.2)
        ax.set_yscale("log")
        ax.set_xlabel("Kinetic energy at detector (keV)")
        ax.set_ylabel("Counts (log scale)")
        ax.set_title(f"{PARTICLE_LABELS[p]}")
        if xlims[p]:
            ax.set_xlim(*xlims[p])
        ax.xaxis.set_minor_locator(AutoMinorLocator())

    fig.suptitle(
        f"Detector Energy Spectra — B-10 fraction = {SELECTED_FRACTION*100:.1f} %  "
        f"|  Thickness = {GRAPHENE_UM} µm  ({N_NEUTRONS:,} neutrons)",
        fontsize=13,
    )
    fig.tight_layout()
    save(fig, "06_detector_energy_spectra.png")


# ── 07. Creation vs detector energy comparison ─────────────────────────────────
def plot_creation_vs_detector(data_by_fraction: dict):
    key = SELECTED_FRACTION
    if key not in data_by_fraction:
        print(f"  [WARN] plot 07: fraction {key*100:.2f} % not available")
        return

    cap = data_by_fraction[key]["captura"]
    det = data_by_fraction[key]["detector"]

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    for ax, p in zip(axes, ["alpha", "Li7"]):
        vals_c = cap.loc[cap["ParticleNorm"] == p, "KineticEnergy_MeV"].values
        vals_d = (det.loc[
            (det["ParticleNorm"] == p) & (det["VertexVolume"] == "graphene"),
            "KineticEnergy_keV"
        ].values / 1e3)

        if len(vals_c) == 0 and len(vals_d) == 0:
            ax.set_visible(False)
            continue

        e_max = max(
            vals_c.max() if len(vals_c) else 0,
            vals_d.max() if len(vals_d) else 0,
        ) * 1.05
        bins = np.linspace(0, e_max, 60)

        if len(vals_c):
            ax.hist(vals_c, bins=bins, histtype="stepfilled",
                    alpha=0.55, color=COLORS[p], label="Creation")
        if len(vals_d):
            ax.hist(vals_d, bins=bins, histtype="step",
                    lw=2.0, color="black", label="At detector")

        ax.set_yscale("log")
        ax.set_xlabel("Energy (MeV)")
        ax.set_ylabel("Counts (log scale)")
        ax.set_title(f"{PARTICLE_LABELS[p]}")
        ax.legend()
        ax.xaxis.set_minor_locator(AutoMinorLocator())

    fig.suptitle(
        f"Creation vs Detection Energy — B-10 = {SELECTED_FRACTION*100:.1f} %  "
        f"|  Thickness = {GRAPHENE_UM} µm",
        fontsize=13,
    )
    fig.tight_layout()
    save(fig, "07_creation_vs_detector_energy.png")


# ── 08. Mean ion range vs boron fraction ──────────────────────────────────────
def plot_ion_ranges(df: pd.DataFrame):
    fig, ax = plt.subplots(figsize=(8, 5))
    for p in ["alpha", "Li7"]:
        col = f"range_{p}_um"
        if col in df.columns:
            ax.plot(df["boron_pct"], df[col],
                    "D", color=COLORS[p], ms=7, label=PARTICLE_LABELS[p])
    ax.set_xlabel(xlabel_boron())
    ax.set_ylabel("Mean range (µm)")
    ax.set_title(fr"Mean Range of $\alpha$ and Li-7 Ions in Graphene vs Boron Fraction"
                 f"\n(Graphene thickness = {GRAPHENE_UM} µm)")
    ax.legend()
    minor_ticks(ax)
    fig.tight_layout()
    save(fig, "08_ion_range_vs_boron.png")


# ── 09. All three species energies in one figure ───────────────────────────────
def plot_all_species_energy(data_by_fraction: dict):
    key = SELECTED_FRACTION
    if key not in data_by_fraction:
        print(f"  [WARN] plot 09: fraction {key*100:.2f} % not available")
        return

    cap = data_by_fraction[key]["captura"]
    det = data_by_fraction[key]["detector"]

    fig, axes = plt.subplots(2, 3, figsize=(16, 9))
    xlims_mev = {"alpha": None, "Li7": None, "gamma": (0, 2)}
    xlims_kev = {"alpha": None, "Li7": None, "gamma": (0, 2000)}

    for col_idx, p in enumerate(PARTICLES):
        ax_top = axes[0, col_idx]
        vals_c = cap.loc[cap["ParticleNorm"] == p, "KineticEnergy_MeV"].values
        if len(vals_c):
            xl = xlims_mev[p]
            xmax = xl[1] if xl else vals_c.max() * 1.05
            bins = np.linspace(0, xmax, 70)
            ax_top.hist(vals_c, bins=bins, histtype="stepfilled",
                        color=COLORS[p], alpha=0.75, edgecolor=COLORS[p], lw=1.0)
            if xl:
                ax_top.set_xlim(*xl)
        ax_top.set_xlabel("Creation energy (MeV)")
        ax_top.set_ylabel("Counts")
        ax_top.set_title(f"{PARTICLE_LABELS[p]} — Creation")
        ax_top.xaxis.set_minor_locator(AutoMinorLocator())
        ax_top.yaxis.set_minor_locator(AutoMinorLocator())

        ax_bot = axes[1, col_idx]
        mask_d = (det["ParticleNorm"] == p) & (det["VertexVolume"] == "graphene")
        vals_d = det.loc[mask_d, "KineticEnergy_keV"].values
        if len(vals_d):
            xl = xlims_kev[p]
            xmax = xl[1] if xl else vals_d.max() * 1.05
            bins = np.linspace(0, xmax, 70)
            ax_bot.hist(vals_d, bins=bins, histtype="stepfilled",
                        color=COLORS[p], alpha=0.75, edgecolor=COLORS[p], lw=1.0)
            ax_bot.set_yscale("log")
            if xl:
                ax_bot.set_xlim(*xl)
        ax_bot.set_xlabel("Energy at detector (keV)")
        ax_bot.set_ylabel("Counts (log scale)")
        ax_bot.set_title(f"{PARTICLE_LABELS[p]} — At Detector")
        ax_bot.xaxis.set_minor_locator(AutoMinorLocator())

    fig.suptitle(
        fr"Energy Spectra — All Species — B-10 = {SELECTED_FRACTION*100:.1f} %  "
        f"|  Thickness = {GRAPHENE_UM} µm"
        f"\nTop: creation  |  Bottom: at sensitive detector",
        fontsize=13,
    )
    fig.tight_layout()
    save(fig, "09_all_species_energy.png")


# ── 00. Summary 2×2 panel ──────────────────────────────────────────────────────
def plot_summary_panel(df: pd.DataFrame):
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    ax1, ax2, ax3, ax4 = axes.flat

    ax1.plot(df["boron_pct"], df["efficiency_%"], "o", color="#e74c3c", ms=6)
    ax1.set_title("Capture Efficiency (%)")
    ax1.set_xlabel(xlabel_boron())
    ax1.set_ylabel("%")

    for p in PARTICLES:
        ax2.plot(df["boron_pct"], df[f"created_{p}"],
                 "o", color=COLORS[p], ms=5, label=PARTICLE_LABELS[p])
    ax2.set_title("Particles Created in Graphene")
    ax2.set_xlabel(xlabel_boron())
    ax2.set_ylabel("Counts")
    ax2.legend()

    for p in PARTICLES:
        ax3.plot(df["boron_pct"], df[f"det_{p}"],
                 "s", color=COLORS[p], ms=5, label=PARTICLE_LABELS[p])
    ax3.set_yscale("log")
    ax3.set_title("Particles at Detector (log scale)")
    ax3.set_xlabel(xlabel_boron())
    ax3.set_ylabel("Counts")
    ax3.legend()

    for p in PARTICLES:
        created = df[f"created_{p}"]
        det_    = df[f"det_{p}"]
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            frac = np.where(created > 0, 100.0 * det_ / created, 0.0)
        ax4.plot(df["boron_pct"], frac,
                 "^", color=COLORS[p], ms=5, label=PARTICLE_LABELS[p])
    ax4.set_title("Fraction Reaching Detector (%)")
    ax4.set_xlabel(xlabel_boron())
    ax4.set_ylabel("%")
    ax4.legend()

    for ax in axes.flat:
        ax.grid(True, alpha=0.4)
        ax.xaxis.set_minor_locator(AutoMinorLocator())

    fig.suptitle(
        f"Summary — B-10 Doped Graphene Neutron Detector\n"
        f"Varying Boron Fraction  |  Thickness = {GRAPHENE_UM} µm  |  {N_NEUTRONS:,} neutrons",
        fontsize=14, y=1.01,
    )
    fig.tight_layout()
    save(fig, "00_summary_panel.png")


# ══════════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════════
def main():
    print(f"\nSearching ROOT files in : {BUILD_DIR}")
    print(f"Saving plots to         : {PLOT_DIR}")
    print(f"Graphene thickness      : {GRAPHENE_UM} µm (fixed)")
    print(f"Selected fraction       : {SELECTED_FRACTION*100:.1f} %\n")

    data_by_fraction: dict = {}
    for frac in BORON_FRACTIONS:
        label = f"output_{root_name(frac)}"
        print(f"  Reading {root_name(frac)} ...", end=" ")
        data = load_root(frac)
        if data is not None:
            data_by_fraction[frac] = data
            print(f"OK  |  ProductosCaptura: {len(data['captura']):6d}"
                  f"  |  ParticulasDetector: {len(data['detector']):6d}")
        else:
            print("NOT AVAILABLE")

    if not data_by_fraction:
        sys.exit("\n[ERROR] No ROOT files found. Run run_simulations_boron.py first.")

    df = compute_metrics(data_by_fraction)

    # ── Console table ──────────────────────────────────────────────────────────
    print("\n" + "="*85)
    print(f"{'Boron %':>10}  {'Eff.%':>7}  "
          f"{'α_created':>10}  {'Li7_cre':>8}  {'γ_cre':>8}  "
          f"{'α_det':>7}  {'Li7_det':>7}  {'γ_det':>7}")
    print("-"*85)
    for _, row in df.iterrows():
        print(f"{row['boron_pct']:>8.2f} %   "
              f"{row['efficiency_%']:>6.3f}%  "
              f"{row['created_alpha']:>10.0f}  "
              f"{row['created_Li7']:>8.0f}  "
              f"{row['created_gamma']:>8.0f}  "
              f"{row['det_alpha']:>7.0f}  "
              f"{row['det_Li7']:>7.0f}  "
              f"{row['det_gamma']:>7.0f}")
    print("="*85 + "\n")

    csv_path = PLOT_DIR / "metrics_boron.csv"
    df.to_csv(csv_path, index=False, float_format="%.4f")
    print(f"  [CSV]  Table saved to {csv_path.name}\n")

    print("Generating plots...")
    plot_efficiency(df)
    plot_created_particles(df)
    plot_detected_particles(df)
    plot_transmission_fraction(df)
    plot_creation_spectra(data_by_fraction)
    plot_detector_spectra(data_by_fraction)
    plot_creation_vs_detector(data_by_fraction)
    plot_ion_ranges(df)
    plot_all_species_energy(data_by_fraction)
    plot_summary_panel(df)

    print(f"\nDone. {len(list(PLOT_DIR.glob('*.png')))} plots saved to {PLOT_DIR}")


if __name__ == "__main__":
    main()
