/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# --- Espesores del detector ---
# Cambiar aqui antes de cada run. Geant4 reinicializa la geometria
# automaticamente en el siguiente /run/beamOn.
/detector/grapheneThickness 5 um
/detector/kaptonThickness   9 um

/gun/particle neutron
/gun/energy 0.025 eV
/gun/position 0 0 -1.5 cm
/gun/direction 0 0 1
/gun/number 1

/run/beamOn 100000
