/control/verbose 0
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# --- Espesores ---
/detector/grapheneThickness 5 um
/detector/kaptonThickness   125 um
/detector/boronFraction     0.3

# --- Orden de capas: kaptonFirst (default) o grapheneFirst ---
/detector/order kaptonFirst

# --- Grafeno activo: true (default) o false ---
/detector/enableGraphene false

/run/initialize

/run/beamOn 1000000
