/control/verbose 2
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# --- Espesores del detector ---
/detector/grapheneThickness 30 um
/detector/kaptonThickness   120 um
/detector/boronFraction     0.05

# --- Orden de capas: kaptonFirst (default) o grapheneFirst ---
/detector/order kaptonFirst

# --- Grafeno activo: true (default) o false ---
/detector/enableGraphene true

/run/initialize

# Visualización
/vis/open OGL
/vis/viewer/set/viewpointThetaPhi 30 30
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh true
/vis/scene/create
/vis/scene/add/volume
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/hits

# Colores por tipo de partícula
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma  green
/vis/modeling/trajectories/drawByParticleID-0/set e-     red
/vis/modeling/trajectories/drawByParticleID-0/set alpha  cyan
/vis/modeling/trajectories/drawByParticleID-0/set Li7    green
/vis/modeling/trajectories/drawByParticleID-0/set proton magenta
/vis/scene/endOfEventAction accumulate
/vis/enable
/vis/viewer/refresh

# Decorations
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.5 -.9 20 ! ! Phase 2 : Capture
/vis/set/textLayout
/vis/set/textColour

/vis/scene/add/axes -1.5 -1.5 0 4 cm

# Simulación
/run/beamOn 1
