/control/verbose 2
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/run/initialize

# Visualización
/vis/open OGL
/vis/viewer/set/viewpointThetaPhi 30 30
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh true
/vis/scene/create
/vis/scene/add/volume
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate
/vis/enable
/vis/viewer/refresh

# Decorations
# Name
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.5 -.9 20 ! ! Phase 2 : Capture
/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)

/vis/scene/add/axes -1.5 -1.5 0 4 cm

# Configuración del haz
/gun/particle neutron
/gun/energy 0.025 eV
/gun/position 0 0 -6.5 cm
/gun/direction 0 0 1
/gun/number 1

# Simulación
/run/beamOn 0


